language: cpp
sudo: false
dist: trusty
cache:
  ccache: true
env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1
matrix:
  include:
    - os: linux
      addons: &1
        apt:
          packages:
            - cmake3
            - cmake3-data
            - g++-4.6
            - gcc-4.6
      env:
        - CXX_COMPILER='g++-4.6'
        - C_COMPILER='gcc-4.6'
        - BUILD_TYPE='Release'
    - os: linux
      addons:
        apt:
          packages:
            - cmake3
            - cmake3-data
            - clang
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
        - BUILD_TYPE='Release'

    - os: osx
      osx_image: xcode7.3
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
        - BUILD_TYPE='Release'
    - os: osx
      osx_image: xcode7.3
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - BUILD_TYPE='Release'
        - HOMEBREW_GCC='gcc@7'

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install ${HOMEBREW_GCC} ccache cmake zlib
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
before_script:
  - ./.ci/report_versions.sh
  - cd ${TRAVIS_BUILD_DIR}
script:
  - cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build build -- VERBOSE=1
